package com.fastflow.app.presentation.theme

import androidx.compose.ui.graphics.Color

val PrimaryGreen = Color(0xFF2E7D52)
val AccentBlue = Color(0xFF2E7D52)
val AccentOrange = Color(0xFFE8845A)
val BackgroundLight = Color(0xFFF4F8F5)
val TextAnthracite = Color(0xFF1C3A2A)

val md_theme_light_primary = Color(0xFF2E7D52)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFB7E4C7)
val md_theme_light_onPrimaryContainer = Color(0xFF00391A)
val md_theme_light_secondary = Color(0xFF52A87A)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCCEDD8)
val md_theme_light_onSecondaryContainer = Color(0xFF00391A)
val md_theme_light_background = Color(0xFFF4F8F5)
val md_theme_light_onBackground = Color(0xFF1C3A2A)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF1C3A2A)
val md_theme_light_surfaceVariant = Color(0xFFDCEDE3)
val md_theme_light_onSurfaceVariant = Color(0xFF3D5445)
val md_theme_light_outline = Color(0xFF6E9A7E)

val md_theme_dark_primary = Color(0xFF74C896)
val md_theme_dark_onPrimary = Color(0xFF003920)
val md_theme_dark_primaryContainer = Color(0xFF1A5E38)
val md_theme_dark_onPrimaryContainer = Color(0xFFB7E4C7)
val md_theme_dark_secondary = Color(0xFFFFB59A)
val md_theme_dark_onSecondary = Color(0xFF5C1900)
val md_theme_dark_secondaryContainer = Color(0xFF7D3014)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDDD1)
val md_theme_dark_background = Color(0xFF0F1F16)
val md_theme_dark_onBackground = Color(0xFFD8EDDF)
val md_theme_dark_surface = Color(0xFF0F1F16)
val md_theme_dark_onSurface = Color(0xFFD8EDDF)
val md_theme_dark_surfaceVariant = Color(0xFF1E3328)
val md_theme_dark_onSurfaceVariant = Color(0xFFA0C8AE)
val md_theme_dark_outline = Color(0xFF4E7A5E)
